'use strict';
/**
 * MELAKA FORGE — THE CAST
 * =======================
 * One entry per portrait. Every entry is a full skeleton + costume brief drawn
 * from `src/data/npcs.json` and the design docs — no character inherits another
 * character's head. Seeds are fixed strings, so output is byte-stable.
 *
 * Design notes are deliberately in the data: the file is the character sheet.
 */

const CAST = [
  // -------------------------------------------------------------------------
  {
    id: 'fernao-gomes', name: 'Fernão Gomes', culture: 'portuguese', seed: 'gomes-1580',
    brief: 'Spice merchant in his fifties; anxiety worn into the brow, a ledger-keeper losing his credit.',
    backdrop: 'warehouse-timber',
    head: { skull: 'long', cx: 35, top: 6, chinY: 53, halfW: 16.0, turn: 0.72,
      jawScale: 0.94, cheekBone: 0.96, browY: 0.435, eyeY: 0.52, noseBaseY: 0.7, mouthY: 0.822,
      noseBreak: 1.2, earSize: 1.0, neckW: 0.46, neckLen: 6, neckTilt: 0.6 },
    face: { brow: 'worried', eye: 'deepset', nose: 'aquiline', mouth: 'downturn',
      age: 0.62, cheekHollow: 0.45, eyeGapNear: 0.42, eyeGapFar: 0.33, eyeW: 0.44 },
    hair: { style: 'balding', mat: 'hair-saltpep', part: -0.5 },
    beard: { style: 'pointed', mat: 'hair-saltpep' },
    moustache: { style: 'full', mat: 'hair-saltpep' },
    headwear: { style: 'none' },
    body: { shoulderRaise: -3, shift: 1, shoulderW: 2.15, shoulderRun: 10, lean: 0.5, shoulderDrop: 0.7, roundShoulder: 0.62 },
    garment: { mat: 'wool-charcoal', collar: 'ruff', accessories: ['chain'] },
  },
  // -------------------------------------------------------------------------
  {
    id: 'capitao-rodrigues', name: 'Capitão Rodrigues', culture: 'portuguese-sun', seed: 'rodrigues-garrison',
    brief: 'Garrison captain: square skull under a morion, campaign scar, jaw like a bollard.',
    backdrop: 'fort-stone',
    head: { skull: 'square', cx: 44, top: 9, chinY: 56, halfW: 19.0, turn: -0.66,
      jawScale: 1.10, cheekBone: 1.02, browY: 0.43, eyeY: 0.515, noseBaseY: 0.7, mouthY: 0.822,
      earSize: 0.9, neckW: 0.64, neckLen: 3, neckTilt: -0.4 },
    face: { brow: 'angled', eye: 'squint', nose: 'broad', mouth: 'set',
      age: 0.5, cheekBoneHi: 0.8, eyeGapNear: 0.43, eyeGapFar: 0.34, eyeW: 0.42,
      scar: [30, 20, 27, 30] },
    hair: { style: 'wrapped', mat: 'hair-darkbrown' },
    beard: { style: 'short-full', mat: 'hair-darkbrown' },
    moustache: { style: 'walrus', mat: 'hair-darkbrown' },
    headwear: { style: 'morion', mat: 'steel' },
    body: { shoulderRaise: -3, shift: -2, shoulderW: 2.75, shoulderRun: 7, lean: -0.3, shoulderDrop: 0.0, roundShoulder: 0.4 },
    garment: { mat: 'leather', collar: 'none', accessories: ['gorget', { name: 'sash', side: 1 }] },
  },
  // -------------------------------------------------------------------------
  {
    id: 'padre-tomas', name: 'Padre Tomás', culture: 'portuguese', seed: 'tomas-jesuit',
    brief: 'Gaunt Jesuit; tonsure, hollow cheeks, eyes kind and certain in equal measure.',
    backdrop: 'church-stone',
    head: { skull: 'gaunt', cx: 33, top: 2, chinY: 48, halfW: 13.8, turn: 0.62,
      jawScale: 0.88, cheekBone: 0.86, browY: 0.425, eyeY: 0.505, noseBaseY: 0.7, mouthY: 0.832,
      earSize: 1.15, neckW: 0.42, neckLen: 7, neckTilt: 0.3 },
    face: { brow: 'thin', eye: 'deepset', nose: 'fine', mouth: 'full',
      age: 0.55, cheekHollow: 1.0, eyeGapNear: 0.41, eyeGapFar: 0.32, eyeW: 0.43 },
    hair: { style: 'tonsure', mat: 'hair-grey', part: 0 },
    beard: { style: 'stubble', mat: 'hair-grey' },
    moustache: { style: 'none' },
    headwear: { style: 'none' },
    body: { shoulderRaise: -3, shift: 2, shoulderW: 1.66, shoulderRun: 12, lean: 0.2, shoulderDrop: -0.6, roundShoulder: 0.8 },
    garment: { mat: 'wool-black', collar: 'clerical' },
  },
  // -------------------------------------------------------------------------
  {
    id: 'aminah', name: 'Aminah', culture: 'malay', seed: 'aminah-market',
    brief: 'Market vendor, warm brown skin, heart-shaped face; the sharpest pair of eyes on Rua Direita.',
    backdrop: 'market-awning',
    head: { skull: 'heart', cx: 34, top: 8, chinY: 54, halfW: 15.6, turn: -0.74,
      jawScale: 0.86, cheekBone: 1.04, browY: 0.435, eyeY: 0.515, noseBaseY: 0.695, mouthY: 0.818,
      earSize: 0, neckW: 0.43, neckLen: 5, neckTilt: -0.5 },
    face: { brow: 'arched', eye: 'almond', nose: 'button', mouth: 'smirk',
      age: 0.22, cheekBoneHi: 1.0, eyeGapNear: 0.42, eyeGapFar: 0.33, eyeW: 0.45 },
    hair: { style: 'veiled', mat: 'hair-black' },
    beard: { style: 'none' }, moustache: { style: 'none' },
    headwear: { style: 'tudung', mat: 'wool-rust' },
    body: { shoulderRaise: 0, shift: -1, shoulderW: 2.04, shoulderRun: 10, lean: -0.6, shoulderDrop: 0.5, roundShoulder: 0.7 },
    garment: { mat: 'silk-green', collar: 'baju', trimMat: 'brass' },
  },
  // -------------------------------------------------------------------------
  {
    id: 'chen-wei', name: 'Chen Wei', culture: 'chinese', seed: 'chenwei-guild',
    brief: 'Guild man in his sixties: long rectangular face, wispy chin beard, nothing wasted.',
    backdrop: 'counting-house',
    head: { skull: 'long', cx: 41, top: 6, chinY: 53, halfW: 14.0, turn: 0.58,
      jawScale: 1.00, cheekBone: 0.92, browY: 0.445, eyeY: 0.53, noseBaseY: 0.705, mouthY: 0.828,
      earSize: 1.25, neckW: 0.45, neckLen: 6, neckTilt: 0.2 },
    face: { brow: 'straight', eye: 'narrow', nose: 'straight', mouth: 'thin',
      age: 0.78, eyeGapNear: 0.44, eyeGapFar: 0.35, eyeW: 0.46 },
    hair: { style: 'wrapped', mat: 'hair-grey' },
    beard: { style: 'wispy-chin', mat: 'hair-grey' },
    moustache: { style: 'droop', mat: 'hair-grey' },
    headwear: { style: 'futou', mat: 'wool-black' },
    body: { shoulderRaise: -2, shift: 2, shoulderW: 1.9, shoulderRun: 11, lean: 0.3, shoulderDrop: 0.0, roundShoulder: 0.66 },
    garment: { mat: 'wool-indigo', collar: 'mandarin', collarMat: 'linen-white' },
  },
  // -------------------------------------------------------------------------
  {
    id: 'rashid', name: 'Rashid', culture: 'arab', seed: 'rashid-nakhoda',
    brief: 'Omani nakhoda: broad open face, full beard, a laugh that carries across the quay — dignified, never a clown.',
    backdrop: 'harbour-sky',
    head: { skull: 'broad', cx: 35, top: 7, chinY: 50, halfW: 19.0, turn: -0.70,
      jawScale: 1.02, cheekBone: 1.02, browY: 0.44, eyeY: 0.525, noseBaseY: 0.7, mouthY: 0.818,
      noseBreak: 0.9, earSize: 0.8, neckW: 0.58, neckLen: 4, neckTilt: -0.3 },
    face: { brow: 'bushy', eye: 'wide', nose: 'aquiline', mouth: 'smile',
      age: 0.4, cheekBoneHi: 0.7, eyeGapNear: 0.43, eyeGapFar: 0.34, eyeW: 0.45 },
    hair: { style: 'wrapped', mat: 'hair-black' },
    beard: { style: 'full', mat: 'hair-black' },
    moustache: { style: 'full', mat: 'hair-black' },
    headwear: { style: 'turban-omani', mat: 'linen-white' },
    body: { shoulderRaise: -3, shift: -3, shoulderW: 2.34, shoulderRun: 8, lean: -0.4, shoulderDrop: -0.8, roundShoulder: 0.48 },
    garment: { mat: 'linen-white', collar: 'placket', trimMat: 'brass', accessories: [{ name: 'cord', side: -1 }] },
  },
  // -------------------------------------------------------------------------
  {
    id: 'siti', name: 'Siti', culture: 'malay', seed: 'siti-sanctuary',
    brief: 'Seventeen, in sanctuary: small oval face, wide watchful eyes, chin up anyway.',
    backdrop: 'church-dim',
    head: { skull: 'oval', cx: 32, top: 14, chinY: 47, halfW: 13.4, turn: 0.80,
      jawScale: 0.84, cheekBone: 0.94, browY: 0.425, eyeY: 0.505, noseBaseY: 0.69, mouthY: 0.815,
      earSize: 0, neckW: 0.40, neckLen: 6, neckTilt: 0.7 },
    face: { brow: 'arched', eye: 'wide', nose: 'button', mouth: 'pursed',
      age: 0.0, eyeGapNear: 0.41, eyeGapFar: 0.32, eyeW: 0.46 },
    hair: { style: 'veiled', mat: 'hair-black' },
    beard: { style: 'none' }, moustache: { style: 'none' },
    headwear: { style: 'kerchief', mat: 'linen-white' },
    body: { shoulderRaise: 5, shift: 3, shoulderW: 1.62, shoulderRun: 12, lean: 0.7, shoulderDrop: 0.9, roundShoulder: 0.84 },
    garment: { mat: 'cotton-ochre', collar: 'baju', trimMat: 'leather' },
  },
  // -------------------------------------------------------------------------
  {
    id: 'alvares', name: 'Senhor Alvares', culture: 'portuguese', seed: 'alvares-tin',
    brief: 'Tin merchant: angular, slicked, expensive — a cold smirk above a stiff ruff.',
    backdrop: 'tin-store',
    head: { skull: 'diamond', cx: 41, top: 7, chinY: 48, halfW: 16.0, turn: -0.60,
      jawScale: 0.92, cheekBone: 1.08, browY: 0.435, eyeY: 0.515, noseBaseY: 0.7, mouthY: 0.822,
      noseBreak: 0.8, earSize: 0.85, neckW: 0.46, neckLen: 5, neckTilt: -0.2 },
    face: { brow: 'angled', eye: 'hooded', nose: 'long', mouth: 'smirk',
      age: 0.3, cheekBoneHi: 1.1, cheekHollow: 0.5, eyeGapNear: 0.42, eyeGapFar: 0.33, eyeW: 0.43 },
    hair: { style: 'combed', mat: 'hair-black', part: 0.6 },
    beard: { style: 'vandyke', mat: 'hair-black' },
    moustache: { style: 'waxed', mat: 'hair-black' },
    headwear: { style: 'none' },
    body: { shoulderRaise: 4, shift: -1, shoulderW: 2.56, shoulderRun: 8, lean: -0.2, shoulderDrop: -0.5, roundShoulder: 0.45 },
    garment: { mat: 'wool-crimson', collar: 'ruff', accessories: ['chain'] },
  },
  // -------------------------------------------------------------------------
  {
    id: 'mak-enang', name: 'Mak Enang', culture: 'malay', seed: 'makenang-healer',
    brief: 'Kampung healer, seventy-odd: shrunken skull, hooded eyes, a mouth that has said worse to better men.',
    backdrop: 'kampung-attap',
    head: { skull: 'shrunken', cx: 37, top: 13, chinY: 49, halfW: 14.2, turn: 0.68,
      jawScale: 0.90, cheekBone: 0.88, browY: 0.455, eyeY: 0.54, noseBaseY: 0.72, mouthY: 0.845,
      earSize: 1.1, neckW: 0.40, neckLen: 4, neckTilt: 0.9 },
    face: { brow: 'thin', eye: 'hooded', nose: 'bulbous', mouth: 'pursed',
      age: 1.0, cheekHollow: 0.9, eyeGapNear: 0.42, eyeGapFar: 0.33, eyeW: 0.44 },
    hair: { style: 'wrapped', mat: 'hair-silver' },
    beard: { style: 'none' }, moustache: { style: 'none' },
    headwear: { style: 'headwrap', mat: 'batik-plum' },
    body: { shoulderRaise: 4, shift: 2, shoulderW: 1.62, shoulderRun: 13, lean: 0.9, shoulderDrop: 0.8, roundShoulder: 0.88 },
    garment: { mat: 'silk-teal', collar: 'baju', trimMat: 'brass', accessories: ['beads'] },
  },
  // -------------------------------------------------------------------------
  {
    id: 'gaspar-mesquita', name: 'Gaspar Mesquita', culture: 'portuguese', seed: 'gaspar-customs',
    brief: 'Customs inspector: round, fleshy, immaculate; a tall hat doing the work his character cannot.',
    backdrop: 'gate-shadow',
    head: { skull: 'round', cx: 40, top: 8, chinY: 55, halfW: 14.8, turn: 0.64,
      jawScale: 1.06, cheekBone: 1.04, browY: 0.445, eyeY: 0.53, noseBaseY: 0.705, mouthY: 0.828,
      earSize: 0.9, neckW: 0.66, neckLen: 3, neckTilt: 0.2 },
    face: { brow: 'straight', eye: 'narrow', nose: 'bulbous', mouth: 'thin',
      age: 0.42, eyeGapNear: 0.44, eyeGapFar: 0.35, eyeW: 0.42 },
    hair: { style: 'combed', mat: 'hair-brown', part: -0.55 },
    beard: { style: 'none' },
    moustache: { style: 'waxed', mat: 'hair-brown' },
    headwear: { style: 'tall-hat', mat: 'wool-black', bandMat: 'wool-crimson' },
    body: { shoulderRaise: -3, shift: 0, shoulderW: 2.5, shoulderRun: 9, lean: 0.2, shoulderDrop: 0.0, roundShoulder: 0.72 },
    garment: { mat: 'wool-charcoal', collar: 'band', collarMat: 'linen-white', accessories: ['chain'] },
  },
  // -------------------------------------------------------------------------
  {
    id: 'diogo-almeida', name: 'Diogo Almeida', culture: 'portuguese', seed: 'diogo-runner',
    brief: 'Notary runner, twenty-two: narrow triangular face, unruly curls, always half-turned to leave.',
    backdrop: 'street-wall',
    head: { skull: 'heart', cx: 45, top: 11, chinY: 47, halfW: 14.2, turn: -0.86,
      jawScale: 0.82, cheekBone: 0.96, browY: 0.425, eyeY: 0.505, noseBaseY: 0.69, mouthY: 0.812,
      noseBreak: 0.9, earSize: 1.2, neckW: 0.43, neckLen: 6, neckTilt: -0.8 },
    face: { brow: 'straight', eye: 'round', nose: 'long', mouth: 'wide',
      age: 0.0, eyeGapNear: 0.41, eyeGapFar: 0.32, eyeW: 0.45 },
    hair: { style: 'curly', mat: 'hair-darkbrown', part: 0.2 },
    beard: { style: 'stubble', mat: 'hair-darkbrown' },
    moustache: { style: 'none' },
    headwear: { style: 'none' },
    body: { shoulderRaise: 5, shift: -2, shoulderW: 2.02, shoulderRun: 9, lean: -0.8, shoulderDrop: -0.9, roundShoulder: 0.55 },
    garment: { mat: 'linen-cream', collar: 'band', collarMat: 'linen-white', accessories: [{ name: 'strap', side: 1 }] },
  },
  // -------------------------------------------------------------------------
  {
    id: 'lin-mei', name: 'Lin Mei', culture: 'chinese', seed: 'linmei-clerk',
    brief: 'Counting-house clerk: smooth oval face, coiled bun, the calm of someone who has already found the error.',
    backdrop: 'ledger-shelf',
    head: { skull: 'oval', cx: 44, top: 9, chinY: 47, halfW: 13.6, turn: 0.76,
      jawScale: 0.86, cheekBone: 0.98, browY: 0.43, eyeY: 0.512, noseBaseY: 0.692, mouthY: 0.815,
      earSize: 0.7, neckW: 0.42, neckLen: 5, neckTilt: 0.4 },
    face: { brow: 'straight', eye: 'almond', nose: 'fine', mouth: 'set',
      age: 0.1, eyeGapNear: 0.42, eyeGapFar: 0.33, eyeW: 0.45 },
    hair: { style: 'bun', mat: 'hair-black', part: 0, tuckEar: true },
    beard: { style: 'none' }, moustache: { style: 'none' },
    headwear: { style: 'none' },
    body: { shoulderRaise: 0, shift: 1, shoulderW: 1.64, shoulderRun: 11, lean: 0.4, shoulderDrop: 0.4, roundShoulder: 0.78 },
    garment: { mat: 'silk-teal', collar: 'mandarin', collarMat: 'linen-white' },
  },
  // -------------------------------------------------------------------------
  {
    id: 'pak-salleh', name: 'Pak Salleh', culture: 'malay', seed: 'salleh-fisher',
    brief: 'Fisherman-porter: broad flat face burnt by thirty years of glare, twisted tanjak, kain over one shoulder.',
    backdrop: 'river-edge',
    head: { skull: 'broad', cx: 33, top: 7, chinY: 44, halfW: 15.4, turn: -0.62,
      jawScale: 1.04, cheekBone: 1.06, browY: 0.45, eyeY: 0.535, noseBaseY: 0.712, mouthY: 0.838,
      earSize: 1.0, neckW: 0.61, neckLen: 4, neckTilt: -0.2 },
    face: { brow: 'heavy', eye: 'squint', nose: 'broad', mouth: 'wide',
      age: 0.72, cheekBoneHi: 0.9, eyeGapNear: 0.44, eyeGapFar: 0.35, eyeW: 0.43 },
    hair: { style: 'wrapped', mat: 'hair-saltpep' },
    beard: { style: 'stubble', mat: 'hair-saltpep' },
    moustache: { style: 'thin', mat: 'hair-saltpep' },
    headwear: { style: 'tanjak', mat: 'cotton-ochre' },
    body: { shoulderRaise: -1, shift: -1, shoulderW: 2.52, shoulderRun: 8, lean: -0.3, shoulderDrop: 0.8, roundShoulder: 0.5 },
    garment: { bare: true, collar: 'kain', wrapMat: 'batik-plum', side: 1 },
  },
  // -------------------------------------------------------------------------
  {
    id: 'rudra-mudaliar', name: 'Rudra Mudaliar', culture: 'tamil', seed: 'rudra-textile',
    brief: 'Coromandel textile merchant: long face, strong nose, full moustache, gold hoop — his own face at last.',
    backdrop: 'textile-bolts',
    head: { skull: 'long', cx: 44, top: 5, chinY: 50, halfW: 15.0, turn: 0.70,
      jawScale: 0.98, cheekBone: 1.00, browY: 0.442, eyeY: 0.528, noseBaseY: 0.712, mouthY: 0.835,
      noseBreak: 1.4, earSize: 1.15, neckW: 0.53, neckLen: 5, neckTilt: 0.3 },
    face: { brow: 'bushy', eye: 'round', nose: 'hooked', mouth: 'full',
      age: 0.5, cheekBoneHi: 0.8, eyeGapNear: 0.43, eyeGapFar: 0.34, eyeW: 0.46 },
    hair: { style: 'slicked', mat: 'hair-black', part: -0.6 },
    beard: { style: 'none' },
    moustache: { style: 'walrus', mat: 'hair-saltpep' },
    headwear: { style: 'turban-tamil', mat: 'linen-white', accentMat: 'wool-crimson' },
    body: { shoulderRaise: -3, shift: -2, shoulderW: 2.34, shoulderRun: 9, lean: 0.3, shoulderDrop: -0.6, roundShoulder: 0.6 },
    garment: { mat: 'linen-white', collar: 'angavastram', wrapMat: 'linen-cream', borderMat: 'wool-crimson', side: -1, accessories: ['earring'] },
  },
  // -------------------------------------------------------------------------
  {
    id: 'player', name: 'The Traveller', culture: 'portuguese-sun', seed: 'player-traveller',
    brief: 'The player: young, sun-marked, plainly dressed — a face that belongs to whoever is holding the keyboard.',
    backdrop: 'harbour-sky',
    head: { skull: 'oval', cx: 40, top: 14, chinY: 52, halfW: 14.8, turn: -0.72,
      jawScale: 0.96, cheekBone: 1.00, browY: 0.435, eyeY: 0.515, noseBaseY: 0.7, mouthY: 0.822,
      earSize: 1.0, neckW: 0.51, neckLen: 5, neckTilt: -0.4 },
    face: { brow: 'straight', eye: 'almond', nose: 'straight', mouth: 'set',
      age: 0.08, cheekBoneHi: 0.5, eyeGapNear: 0.42, eyeGapFar: 0.33, eyeW: 0.45 },
    hair: { style: 'short-crop', mat: 'hair-brown', part: -0.3 },
    beard: { style: 'stubble', mat: 'hair-brown' },
    moustache: { style: 'none' },
    headwear: { style: 'none' },
    body: { shoulderRaise: 1, shift: 0, shoulderW: 2.12, shoulderRun: 10, lean: -0.2, shoulderDrop: 0.0, roundShoulder: 0.64 },
    garment: { mat: 'leather', collar: 'doublet', shirtMat: 'linen-cream', buttonMat: 'brass' },
  },
];

module.exports = { CAST };
