/**
 * TileVariantSystem
 *
 * Resolves which procedurally-generated tile variant texture to use for a
 * given map cell.  Variants are deterministic — the same (x, y) coordinate
 * always produces the same variant — so the map looks stable across renders
 * and session loads without persisting any extra state.
 *
 * Variant textures are pre-loaded by BootScene using keys of the form:
 *   `${prefix}-var-${index}`   e.g.  "cobblestone-var-3"
 *
 * The system maps canonical base-tile IDs (from runtime-asset-manifest.json)
 * to their variant prefix, then picks a variant index with a simple position-
 * seeded hash so neighbouring tiles naturally differ.
 */

// ── Types ─────────────────────────────────────────────────────────────────────

/** Shape of the tileVariants block in runtime-asset-manifest.json */
export type TileVariantManifest = Record<string, number>;

/** A tile-type identifier as used in tilemap data / manifest */
export type BaseTileId = string;

// ── Mapping from manifest base-tile names → variant prefix ────────────────────
// "prefix" must exactly match the filenames generated by gen_tile_variants.py
// and the prefix used in BootScene.ts TILE_VARIANTS loader.

const BASE_TO_VARIANT_PREFIX: Record<BaseTileId, string> = {
  // Manifest name               Variant prefix (matches gen_tile_variants.py)
  'cobblestone':                 'cobblestone',
  'cobblestone-v1':              'cobblestone',
  'cobblestone-v2':              'cobblestone',
  'cobblestone-v3':              'cobblestone',
  'fortress-stone':              'fortress',
  'fortress-stone-v1':           'fortress',
  'fortress-stone-v2':           'fortress',
  'dirt-path':                   'dirt',
  'dirt-path-v1':                'dirt',
  'dirt-path-v2':                'dirt',
  'grass-tropical':              'grass',
  'grass':                       'grass',
  'grass-v1':                    'grass',
  'grass-v2':                    'grass',
  'water-tile':                  'water',
  'thatch-roof':                 'thatch',
};

/** Variant counts per prefix — must match tileVariants in the manifest */
const VARIANT_COUNTS: Record<string, number> = {
  cobblestone: 8,
  fortress:    7,
  dirt:        6,
  grass:       8,
  water:       6,
  thatch:      6,
};

// ── Hash function ──────────────────────────────────────────────────────────────

/**
 * Deterministic hash of (x, y) → 0..range-1
 * Uses a simple integer hash mixing prime constants.
 */
function positionHash(x: number, y: number, range: number): number {
  // Wang hash-style mixing — cheap and sufficiently uniform
  let h = (x * 1619) ^ (y * 31337);
  h = ((h >>> 16) ^ h) * 0x45d9f3b;
  h = ((h >>> 16) ^ h) * 0x45d9f3b;
  h =  (h >>> 16) ^ h;
  return Math.abs(h) % range;
}

// ── Public API ────────────────────────────────────────────────────────────────

/**
 * Returns true if a given base tile ID has generated variants registered.
 */
export function hasTileVariants(baseTileId: BaseTileId): boolean {
  const prefix = BASE_TO_VARIANT_PREFIX[baseTileId];
  return !!prefix && VARIANT_COUNTS[prefix] > 0;
}

/**
 * Returns the Phaser texture key for the variant to use at map position (x, y).
 * Falls back to `baseTileId` (the non-variant texture) if no variants exist.
 *
 * @param baseTileId  Tile type name as found in runtime-asset-manifest tiles arrays
 * @param tileX       Integer tile column in the map
 * @param tileY       Integer tile row in the map
 */
export function getTileVariantKey(
  baseTileId: BaseTileId,
  tileX: number,
  tileY: number
): string {
  const prefix = BASE_TO_VARIANT_PREFIX[baseTileId];
  if (!prefix) return baseTileId;

  const count = VARIANT_COUNTS[prefix];
  if (!count) return baseTileId;

  const idx = positionHash(tileX, tileY, count);
  return `${prefix}-var-${idx}`;
}

/**
 * Convenience: given a Phaser Tilemap layer, replaces the texture on every
 * tile whose base type has variants with the deterministic variant texture.
 *
 * Call this once after your tilemap layer is created, before the first render.
 *
 * @param layer   A Phaser.Tilemaps.TilemapLayer
 * @param scene   The current Phaser.Scene (for texture lookup)
 * @param tileIdToName  Mapping from Tiled GID → manifest base tile name
 *                      so the system knows which base-type each cell is.
 */
export function applyTileVariantsToLayer(
  layer: Phaser.Tilemaps.TilemapLayer,
  scene: Phaser.Scene,
  tileIdToName: Record<number, BaseTileId>
): void {
  const tiles = layer.layer.data;

  for (let row = 0; row < tiles.length; row++) {
    for (let col = 0; col < tiles[row].length; col++) {
      const tile = tiles[row][col];
      if (!tile || tile.index < 0) continue;  // empty cell

      const baseName = tileIdToName[tile.index];
      if (!baseName || !hasTileVariants(baseName)) continue;

      const variantKey = getTileVariantKey(baseName, col, row);

      // Only swap if the variant texture is actually loaded
      // Phaser.Tilemaps.Tile stores the texture as `tileset` + index;
      // the cleanest runtime override is to swap the texture via the
      // underlying frame — achieved by reassigning the tile's layer texture.
      if (scene.textures.exists(variantKey)) {
        (tile as unknown as { texture: string }).texture = variantKey;
      }
    }
  }
}

/**
 * Build a tileIdToName map from a Phaser Tileset.
 * Assumes each tile in the tileset has a `type` property matching the
 * manifest base tile name (set in Tiled editor under Tile Properties).
 * Falls back to the tile's `name` property, then the tileset name + index.
 *
 * @param tileset  A Phaser.Tilemaps.Tileset
 */
export function buildTileIdToNameMap(
  tileset: Phaser.Tilemaps.Tileset
): Record<number, BaseTileId> {
  const map: Record<number, BaseTileId> = {};
  const firstGid = tileset.firstgid;
  const total = tileset.total;

  for (let i = 0; i < total; i++) {
    const gid = firstGid + i;
    // Phaser stores custom properties set in Tiled under getTileData()
    const data = tileset.getTileData(i) as Record<string, unknown> | null;
    const typeProp  = (data?.type as string) || '';
    const nameProp  = (data?.name as string) || '';
    map[gid] = typeProp || nameProp || `${tileset.name}-${i}`;
  }

  return map;
}
